export const LIST_DAILYREPORT_REQUEST = "@listReportReducer/LIST_DAILYREPORT_REQUEST";
export const LIST_DAILYREPORT_SUCCESS = "@listReportReducer/LIST_DAILYREPORT_SUCCESS";
export const LIST_DAILYREPORT_FAILED = "@listReportReducer/LIST_DAILYREPORT_FAILED";

export const LIST_CHARTREPORT_REQUEST = "@listReportReducer/LIST_CHARTREPORT_REQUEST";
export const LIST_CHARTREPORT_SUCCESS = "@listReportReducer/LIST_CHARTREPORT_SUCCESS";
export const LIST_CHARTREPORT_FAILED = "@listReportReducer/LIST_CHARTREPORT_FAILED";