export const LIST_DAILYREPORT_REQUEST = "@listReportReducer/LIST_DAILYREPORT_REQUEST";
export const LIST_DAILYREPORT_SUCCESS = "@listReportReducer/LIST_DAILYREPORT_SUCCESS";
export const LIST_DAILYREPORT_FAILED = "@listReportReducer/LIST_DAILYREPORT_FAILED";
